#!/usr/bin/env bash

git log -g \
  --pretty=oneline \
  --grep-reflog='commit (amend)' \
  --grep-reflog='rebase: create' \
  --pretty='%H %gD' HEAD \
  | grep "$(git rev-parse $1)" \
  | cut -f2 -d\ \
  | xargs git reflog -n 1 --skip=1 --pretty='%H'